package com.kymokim.spirit.report.entity;

public enum ReportReason {
    INCORRECT_STORE_INFO,
    INCORRECT_MENU_INFO,
    INCORRECT_DRINK_INFO,
    NON_EXISTENT_STORE,
    DUPLICATE_STORE,

    INAPPROPRIATE_LANGUAGE,
    INAPPROPRIATE_PHOTO,
    SPAM_ADVERTISING,
    REPETITIVE_POSTING,
    COPYRIGHT_INFRINGEMENT,

    ETC
}
