#Hibernate
spring.jpa.properties.hibernate.format_sql=true

server.port = 8080

#Actuator
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

management.metrics.enable.system.cpu.usage=true
management.metrics.enable.process.cpu.usage=true
management.metrics.enable.process.memory.used=true

management.prometheus.metrics.enable.system.cpu.usage=true
management.prometheus.metrics.enable.process.cpu.usage=true
management.prometheus.metrics.enable.process.memory.used=true

#redis
spring.redis.host=kymokim.iptime.org
spring.redis.port=11079

#Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#AWS S3
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB