#Hibernate
spring.jpa.properties.hibernate.format_sql=true

server.port = 8080

#Actuator
management.endpoints.web.exposure.include=prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

#Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#AWS S3
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=55MB

#App info
app.version.latest=1.5.5
app.version.required=1.5.2
app.test.mode=true
app.init.latitude=37.5046341625192
app.init.longitude=127.025031333453

spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=2400000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1
