#Hibernate
spring.jpa.properties.hibernate.format_sql=true

server.port = 8080

#Actuator
management.endpoints.web.exposure.include=prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

#Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#AWS S3
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#App info
app.version.latest=1.1.3
app.version.required=1.1.3
app.test.mode=false

spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.max-lifetime=2700000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-test-query=SELECT 1