cloud.aws.credentials.access-key=AKIATUMDOJJ2SBMTGXFZ
cloud.aws.credentials.secret-key=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
cloud.aws.stack.auto=false
cloud.aws.s3.bucket=fooding
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket.url=https://s3.ap-northeast-2.amazonaws.com/fooding
