package com.kymokim.spirit.store.exception;

import com.kymokim.spirit.common.exception.ErrorCode;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum StoreErrorCode implements ErrorCode {
    STORE_NAME_EMPTY(HttpStatus.BAD_REQUEST, 22000, "STORE_NAME_EMPTY"),
    HAS_SCREEN_EMPTY(HttpStatus.BAD_REQUEST, 22001, "HAS_SCREEN_EMPTY"),
    IS_GROUP_AVAILABLE_EMPTY(HttpStatus.BAD_REQUEST, 22002, "IS_GROUP_AVAILABLE_EMPTY"),
    STORE_CATEGORIES_EMPTY(HttpStatus.BAD_REQUEST, 22003, "STORE_CATEGORIES_EMPTY"),
    LOCATION_ADDRESS_EMPTY(HttpStatus.BAD_REQUEST, 22004, "LOCATION_ADDRESS_EMPTY"),
    LOCATION_LATITUDE_EMPTY(HttpStatus.BAD_REQUEST, 22005, "LOCATION_LATITUDE_EMPTY"),
    LOCATION_LONGITUDE_EMPTY(HttpStatus.BAD_REQUEST, 22006, "LOCATION_LONGITUDE_EMPTY"),
    STORE_ORIGIN_IMG_URL_EMPTY(HttpStatus.BAD_REQUEST, 22007, "STORE_ORIGIN_IMG_URL_EMPTY"),
    STORE_OPEN_TIME_EMPTY(HttpStatus.BAD_REQUEST, 22008, "STORE_OPEN_TIME_EMPTY"),
    STORE_CLOSE_TIME_EMPTY(HttpStatus.BAD_REQUEST, 22009, "STORE_CLOSE_TIME_EMPTY"),
    STORE_NOT_FOUND(HttpStatus.NOT_FOUND, 22010, "STORE_NOT_FOUND"),
    STORE_IMG_FILE_EMPTY(HttpStatus.BAD_REQUEST, 22011, "STORE_IMG_FILE_EMPTY"),
    WRONG_OPERATION_INFO(HttpStatus.BAD_REQUEST, 22012, "WRONG_OPERATION_INFO"),
    OWNERSHIP_STORE_NAME_EMPTY(HttpStatus.BAD_REQUEST, 22013, "OWNERSHIP_STORE_NAME_EMPTY"),
    OWNERSHIP_STORE_CONTACT_EMPTY(HttpStatus.BAD_REQUEST, 22014, "OWNERSHIP_STORE_CONTACT_EMPTY"),
    OWNERSHIP_USER_CONTACT_EMPTY(HttpStatus.BAD_REQUEST, 22015, "OWNERSHIP_USER_CONTACT_EMPTY"),
    OWNERSHIP_BUSINESS_NUMBER_EMPTY(HttpStatus.BAD_REQUEST, 22016, "OWNERSHIP_BUSINESS_NUMBER_EMPTY"),
    OWNERSHIP_OPENING_DATE_EMPTY(HttpStatus.BAD_REQUEST, 22017, "OWNERSHIP_OPENING_DATE_EMPTY"),
    OWNERSHIP_LIQUOR_REPORT_EMPTY(HttpStatus.BAD_REQUEST, 22018, "OWNERSHIP_LIQUOR_REPORT_EMPTY"),
    OWNERSHIP_MAIN_REPRESENTATIVE_MISSING(HttpStatus.BAD_REQUEST, 22019, "OWNERSHIP_MAIN_REPRESENTATIVE_MISSING"),
    BUSINESS_REGISTRATION_VALIDATION_FAILED(HttpStatus.BAD_REQUEST, 22020, "BUSINESS_REGISTRATION_VALIDATION_FAILED"),
    OWNERSHIP_ALREADY_REQUESTED(HttpStatus.BAD_REQUEST, 22021, "OWNERSHIP_ALREADY_REQUESTED"),
    OWNERSHIP_NOT_FOUND(HttpStatus.NOT_FOUND, 22022, "OWNERSHIP_NOT_FOUND"),
    STORE_OWNER_ALREADY_EXIST(HttpStatus.BAD_REQUEST, 22023, "STORE_OWNER_ALREADY_EXIST"),
    STORE_OWNER_ALREADY_APPROVE(HttpStatus.BAD_REQUEST, 22024, "STORE_OWNER_ALREADY_APPROVE"),
    OWNERSHIP_REQUESTER_NAME_NOT_MATCHED(HttpStatus.BAD_REQUEST, 22025, "OWNERSHIP_REQUESTER_NAME_NOT_MATCHED"),
    BUSINESS_REGISTRATION_VALIDATE_FAILED(HttpStatus.BAD_REQUEST, 22026, "BUSINESS_REGISTRATION_VALIDATE_FAILED"),
    STORE_SUGGESTION_NOT_FOUND(HttpStatus.NOT_FOUND, 22027, "STORE_SUGGESTION_NOT_FOUND"),
    STORE_IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, 22028, "STORE_IMAGE_NOT_FOUND"),
    INVALID_STORE_IMAGE_RELATION(HttpStatus.BAD_REQUEST, 22029, "INVALID_STORE_IMAGE_RELATION"),
    STORE_UNAUTHORIZED_ACCESS(HttpStatus.BAD_REQUEST, 22030, "STORE_UNAUTHORIZED_ACCESS"),
    BOARD_IMG_FILE_EMPTY(HttpStatus.BAD_REQUEST, 22031, "BOARD_IMG_FILE_EMPTY"),
    BOARD_ORIGIN_IMG_URL_EMPTY(HttpStatus.BAD_REQUEST, 22032, "BOARD_ORIGIN_IMG_URL_EMPTY"),
    BOARD_IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, 22033, "BOARD_IMAGE_NOT_FOUND"),
    INVALID_STORE_BOARD_IMAGE_RELATION(HttpStatus.BAD_REQUEST, 22034, "INVALID_STORE_BOARD_IMAGE_RELATION"),
    INVALID_MANAGER_INVITATION_CODE(HttpStatus.BAD_REQUEST, 22035, "INVALID_MANAGER_INVITATION_CODE"),
    STORE_MANAGER_ALREADY_EXIST(HttpStatus.BAD_REQUEST, 22036, "STORE_MANAGER_ALREADY_EXIST"),
    STORE_MANAGER_NOT_FOUND(HttpStatus.NOT_FOUND, 22037, "STORE_MANAGER_NOT_FOUND"),
    STORE_REQUIRED_INFO_EMPTY(HttpStatus.BAD_REQUEST, 22038, "STORE_REQUIRED_INFO_EMPTY"),
    HAS_ROOM_EMPTY(HttpStatus.BAD_REQUEST, 22039, "HAS_ROOM_EMPTY"),
    IS_PARKING_AVAILABLE_EMPTY(HttpStatus.BAD_REQUEST, 22040, "IS_PARKING_AVAILABLE_EMPTY"),
    IS_CORKAGE_AVAILABLE_EMPTY(HttpStatus.BAD_REQUEST, 22041, "IS_CORKAGE_AVAILABLE_EMPTY"),
    FACILITIES_INFO_EMPTY(HttpStatus.BAD_REQUEST, 22042, "FACILITIES_INFO_EMPTY"),
    HAS_OUTDOOR_EMPTY(HttpStatus.BAD_REQUEST, 22043, "HAS_OUTDOOR_EMPTY"),
    STORE_MOODS_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, 22044, "STORE_MOODS_LIMIT_EXCEEDED"),
    BUSINESS_REGISTRATION_CERTIFICATE_IMAGE_EMPTY(HttpStatus.BAD_REQUEST, 22045, "BUSINESS_REGISTRATION_CERTIFICATE_IMAGE_EMPTY");

    private final HttpStatus httpStatus;
    private final Integer code;
    private final String message;

    StoreErrorCode(HttpStatus httpStatus, Integer code, String message) {
        this.httpStatus = httpStatus;
        this.code = code;
        this.message = message;
    }
}
